package pageobjects.WithPageFactory.Keywords;
/* Auto Generated by TruePath Ultimate Version 1.0.0 */

import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

import pageobjects.WithPageFactory.Keywords.Common_Reusable_actions;
import pageobjects.withoutpagefactory.keywords.PageObject_Keywords;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;


public class Directory
{
	Common_Reusable_actions keywords;
	public Directory(WebDriver driver) 
	{
		PageFactory.initElements(driver, this);
		keywords=new Common_Reusable_actions(driver);
	}

	@FindBy(xpath = "//div[@class='oxd-sheet oxd-sheet--rounded oxd-sheet--white orangehrm-directory-card'][contains(.,'Odis  Adalwin Chief Technical OfficerAdministrationHQ - CA, USA')]")
	public WebElement  odisAdalwinChiefTech;
	
	@FindBy(xpath = "//i[@class='oxd-icon bi-telephone-fill']")
	public WebElement  Call;

	public void CallToUser()
	{
		keywords.ClickOnElement(odisAdalwinChiefTech);
		keywords.ClickOnElement(Call);
	}

}